### ISSUE TITLE
Let's finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s2-evaluacion-intermedia-inesppino#1]
Ahoy @inesppino !!!

Here you have some tips to improve the exercise:

- [x] Add HTML elements for the game: title, label and input, button, space for feedback (`div`, `p`) and number of trials
- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Define the logic to generate and save the random number (remember we gave you a sample code). It should be the first action that happens in our app.
- [x] If you call 'getRandomNumer' function inside the event callback, you will be creating a new random number each time the user clicks the button. That makes the game really complex, and the hints will not have sense. Let's generate the random number when the page loads instead.
- [x] Define the logic to make the counter work
- [ ] Extract the feedback painter to a function
- [x] Fix the if's structure: check for the winner option, then the other and then for the rest is enough with an `else` statement
- [x] Don't use an object to resolve the counter, a good old constant will suffice ;)
- [x] Move variables declaration to the top of the file
- [x] Use `===` instead of `==` for comparisons
- [x] Indent and avoid extra white spaces to improve readability and prevent bugs
- [ ] Try to improve your commit messages, better in English and using imperative. Ex. - > Fix central text

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by inesppino** [comment]
Hidilly-ho @oneeyedman !

I don't know what you mean with "feedback painter to a function".

I think I might have finish to fix all the problems, and the excercie actually works. It would be wonderfull if you can have a look at it!

Thanks!

**Comment by oneeyedman** [comment]
Super well job @inesppino!!

Excellent result! Now, by "Extract the feedback painter to a function" I want you to create a function to write the clues ;)

How about that? Yay or nay?
